version: '3.8'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - NEXT_PUBLIC_API_URL=http://backend:8000
        depends_on:
            - backend
        networks:
            - study-ai-network

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        volumes:
            - ./backend:/app
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/studyai
        depends_on:
            - db
        networks:
            - study-ai-network

    db:
        image: ankane/pgvector:latest
        ports:
            - '5433:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=zany12
            - POSTGRES_DB=studyai
        networks:
            - study-ai-network

volumes:
    postgres_data:

networks:
    study-ai-network:
        external: true
